version: 2.1
orbs: 
  docker: circleci/docker@1.5.0
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: mellib/docker-node-app
    docker:
      - image: circleci/node:latest 
        auth:
          username: $DOCKERHUB_USERNAME 
          password: $DOCKERHUB_PASSWORD
jobs:
  publish-latest-hub:
    executor: docker-publisher
    steps: 
      - checkout
      - setup_remote_docker
      - run:
          name: Published-Docker-Image-to-Docker-Hub
          command: | 
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin 
            docker build -t $IMAGE_NAME . 
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs: 
      - publish-latest-hub
